son=int(input("Istalgan son kiriting: "))
kvadrat=son**2
print(str(son)+" ning kvadrati "+str(kvadrat)+" ga teng")
print(son, "ning kvadrati", son**3,"ga teng")
yosh=int(input("Yoshiz nechida? \n>>>"))
print(f"Siz {2025-yosh} da tug'ilgansiz")
a=float(input("Birinchi sonni kiriting: "))
b=float(input("Ikkinchi sonni kiriting: "))
print(f"{a}+{b}=",a+b)
print(f"{a}-{b}=",a-b)
print(f"{a}*{b}=",a*b)
print(f"{a}/{b}=",a/b)
