davlatlar=["Rossya","O'zbekiston","Hindiston","Xitoy","Yaponiya","Braziliya", "Portugaliya","Argentina","Ispaniya"]
print(davlatlar)
print(sorted(davlatlar))
print(sorted(davlatlar,reverse=True))
print(davlatlar)
davlatlar.reverse()
print(davlatlar)
davlatlar.sort()
print(davlatlar)
davlatlar.sort(reverse=True)
print(davlatlar)
juft_sonlar=list(range(120,1200,2))
print(juft_sonlar)
print(sum(juft_sonlar))
print(min(juft_sonlar))
print(max(juft_sonlar))
print(len(juft_sonlar))
print(juft_sonlar[:20])
print(juft_sonlar[-20:])
print(juft_sonlar[260:280])
print(juft_sonlar[int(len(juft_sonlar)/2)-10 : int(len(juft_sonlar)/2)+10])
taomlar=["Osh","Manti","Xonim","Shorva","Mastava"]
nonushta=taomlar[:]
del nonushta[2]
nonushta.remove("Manti")
nonushta.append("Lag'mon")
nonushta.append("Goja")
print(nonushta)
nonushta=tuple(nonushta)
nonushta.append("qaymoq va non")
print(nonushta)
